apiVersion: v1
kind: ReplicationController
metadata:
 name: mynginxrc
spec:
 replicas: 2
 selector:
  application: nginxapplication
 template:
  metadata:
   name: nginxpod
   labels:
    application: nginxapplication
  spec:
   containers:
   - name: nginxcontainer
     image: nginx
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
 name: myservice
spec: 
 type: ClusterIP
 ports:
  - port: 8080
    targetPort: 80    
 selector:
  application: nginxapplication
