---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
 name: httpdapp
spec:
 selector:
  matchLabels:
   app: httpdlabel
 template:
  metadata:
   name: httpdpod
   labels:
    app: httpdlabel
  spec:
   containers:
   - name: myhttpdcontainer
     image: httpd
     ports: 
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
 name: svc1
spec: 
 type: NodePort
 selector: 
  app: httpdlabel
 ports: 
  - port: 80
    targetPort: 80
