---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: mydeployment
 namespace: example
 labels: 
  app: mynginx
  type: frontend
spec: 
 replicas: 5
 selector: 
  matchLabels: 
   app: mynginx
 template:
  metadata:
   name: mypod
   labels: 
    app: mynginx
    type: frontend
  spec: 
   containers:
    - name: mynginx
      image: nginx:1.7.9
      ports: 
      - containerPort: 80
